#!/sbin/sh


cat /dev/input/event1 > /dev/keycheck&
sleep 2
kill -9 $!
if [ -s /dev/keycheck -o -f /data/local/tmp/cwmrecovery ]
  then

    rm /cache/recovery/boot
    rm -f /data/local/tmp/cwmrecovery
    mount -o remount,rw rootfs /
    umount -l /system
    umount -l /data
    umount -l /cache
    umount -l /mnt/sdcard
    rm -r /sdcard
    rm -r /not/sdcard
    mkdir /sdcard
    mkdir /tmp
    rm /etc
    mkdir /etc
    cp /recovery.fstab /etc/recovery.fstab
    mount /dev/block/mmcblk0p1 /sdcard
if [ -e /sys/devices/platform/mddi_toshiba_hvga/display_driver_info ]
  then 
    cp /sbin/base-rec/recovery-synap /sbin/recovery 
    sleep 1
fi
/sbin/recovery &
/sbin/adbd recovery
fi

# overwrite wlan drivers
	cp /sbin/sdio.ko /system/lib/modules
	cp /sbin/tiwlan_drv.ko /system/lib/modules
	cp /sbin/tiap_drv.ko /system/lib/modules

#remount system to ro for chargemon
	mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier=0,nobh,ro /dev/block/mtdblock0 /system

# Run chargemon 
	/system/bin/chargemon

#continue booting