#!/sbin/sh

cat /dev/input/event1 > /dev/keycheck&
sleep 1
kill -9 $!
if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
  then

    rm /cache/recovery/boot
    mount -o remount,rw rootfs /
    umount -l /system
    umount -l /data
    umount -l /cache
    umount -l /mnt/sdcard
    rm -r /sdcard
    rm -r /not/sdcard
    mkdir /sdcard
    mkdir /tmp
    rm /etc
    mkdir /etc
    cp /recovery.fstab /etc/recovery.fstab
    mount /dev/block/mmcblk0p1 /sdcard
    cp /sbin/aromafm.zip /tmp/aromafm.zip
    inp=`cat /sys/devices/virtual/input/input0/name`
	if [ "$inp" == "synaptics-rmi-touchscreen" ]
	  then
	    cp /sbin/base-rec/recovery-synap /sbin/recovery
	fi
/sbin/recovery &
/sbin/adbd recovery
fi

# link and overwrite wlan drivers
#ln -s -f /modules /system/lib/
    if [ ! -f /system/lib/modules/alfs-modules-9b ]
	then
	  rm -f -r /system/lib/modules
	  ln -s /modules /system/lib/
    fi

#remount system to ro for djcharger
    chown u+s /sbin/djcharger
    mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier=0,nobh,ro /dev/block/mtdblock0 /system

# Run djcharger
     /sbin/djcharger

#continue booting
