#!/sbin/sh


cat /dev/input/event1 > /dev/keycheck&
sleep 1
kill -9 $!
if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then

rm /cache/recovery/boot
mount -o remount,rw rootfs /
umount -l /system
umount -l /data
umount -l /cache
umount -l /mnt/sdcard
rm -r /sdcard
rm -r /not/sdcard
mkdir /sdcard
mkdir /tmp
rm /etc
mkdir /etc
cp /recovery.fstab /etc/recovery.fstab
mount /dev/block/mmcblk0p1 /sdcard
/sbin/recovery &
/sbin/adbd recovery 
fi

/system/bin/chargemon

#continue booting
